//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanvasScriptServer.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CanvasScriptDBContainer : DbContext
    {
        public CanvasScriptDBContainer()
            : base("name=CanvasScriptDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<Scripts> ScriptsSet { get; set; }
        public virtual DbSet<UserNames> UserNamesSet { get; set; }
    }
}
