//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNamesSet
    {
        public string Name { get; set; }
        public int User_Id { get; set; }
    
        public virtual UsersSet UsersSet { get; set; }
    }
}
